[project]
name = "judging"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "rich>=14.0.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
